apps/home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView,VentaView

app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='homeapp'),
    path('ventas/', VentaView.as_view(), name='ventasapp'),
    # Include other app URLs here
]

apps/productos/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import CategoriaListView, MedidaListView, CategoriaCreateView, MedidaCreateView,categoria_detail

app_name = 'productos'

urlpatterns = [
    path('categorias/', CategoriaListView.as_view(), name='categoria-list'),
    path('categorias/create/', CategoriaCreateView.as_view(), name='categoria-create'),
    path('medidas/', MedidaListView.as_view(), name='medida-list'),    
    path('medidas/create/', MedidaCreateView.as_view(), name='medida-create'),
    path('categoria/<int:pk>/', categoria_detail, name='categoria-detail'),
    # Add other product-related URL patterns here
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView,VentaView, bienvenida,contacto,about

app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='homeapp'),
    path('ventas/', VentaView.as_view(), name='ventasapp'),
    path('bienvenida/', bienvenida, name='bienvenida'),
    path('contacto/<str:correo>', contacto, name='contacto'),
    path('about/', about, name='about'),
    # Include other app URLs here
]

inventory_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('apps.home.urls','home')),
    path('products/', include('apps.productos.urls','products')),
    # Include other app URLs here
]

apps/home/models.py
from django.db import models

# Create your models here.

apps/productos/models.py
# Create your models here.
from django.db import models

class Categoria(models.Model):
    categoria = models.CharField(max_length=45, null=True, blank=True)
    habilitado = models.BooleanField(null=True)
    es_producto = models.BooleanField(null=True)

class Medida(models.Model):
    medida = models.CharField(max_length=45, null=True, blank=True)
    es_producto = models.BooleanField(null=True)

class Derivado(models.Model):
    derivado = models.CharField(max_length=45, null=True, blank=True)
    medida = models.ForeignKey(Medida, on_delete=models.PROTECT)
    factorconversion = models.FloatField(null=True, blank=True)

class Proveedor(models.Model):
    nombre = models.CharField(max_length=255, null=True, blank=True)
    contacto = models.CharField(max_length=100, null=True, blank=True)
    direccion = models.CharField(max_length=255, null=True, blank=True)
    nit = models.CharField(max_length=15, null=True, blank=True)
    observaciones = models.TextField(null=True, blank=True)
    habilitado = models.BooleanField(null=True)
    es_producto = models.BooleanField(null=True)
    saldo = models.FloatField(null=True, blank=True)

class Producto(models.Model):  # Renombrado de Medicamento
    codigo = models.CharField(max_length=30, null=True, blank=True)
    nombre = models.CharField(max_length=100, null=True, blank=True)
    nombregenerico = models.CharField(max_length=100, null=True, blank=True)
    descripcion = models.CharField(max_length=100, null=True, blank=True)
    precio = models.FloatField(null=True, blank=True)
    habilitado = models.BooleanField(null=True)
    maximo = models.IntegerField(null=True, blank=True)
    minimo = models.IntegerField(null=True, blank=True)
    composicion = models.CharField(max_length=255, null=True, blank=True)
    presentacion = models.CharField(max_length=255, null=True, blank=True)
    es_producto = models.BooleanField(null=True)
    proveedor = models.ForeignKey(Proveedor, null=True, blank=True, on_delete=models.PROTECT)
    medida = models.ForeignKey(Medida, on_delete=models.PROTECT)
    categoria = models.ForeignKey(Categoria, null=True, blank=True, on_delete=models.PROTECT)
    laboratorio_id = models.IntegerField(null=True, blank=True)  # Cambia por ForeignKey si tienes modelo Laboratorio

class ProductoLugar(models.Model):  # Renombrado de MedicamentoLugar
    existencia = models.FloatField(null=True, blank=True)
    habilitado = models.BooleanField(null=True)
    producto = models.ForeignKey(Producto, on_delete=models.PROTECT)
    

class Lote(models.Model):
    existencia = models.FloatField(null=True, blank=True)
    costo = models.FloatField(null=True, blank=True)
    costodescuento = models.FloatField(null=True, blank=True)
    fechaingreso = models.DateField(null=True, blank=True)
    terminado = models.FloatField(null=True, blank=True)
    lotetotal = models.FloatField(null=True, blank=True)
    fecha_vencimiento = models.DateField(null=True, blank=True)
    productolugar = models.ForeignKey(ProductoLugar, on_delete=models.PROTECT)

apps/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class HomeView(TemplateView):
    template_name = 'home.html'

class VentaView(TemplateView):
    template_name = 'ventas.html'

apps/productos/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from .models import Categoria, Medida
from django.urls import reverse_lazy
from django.http import JsonResponse

# Create your views here.
class CategoriaListView(ListView):
    model = Categoria
    template_name = 'categoria_list.html'
    context_object_name = 'categorias'

class CategoriaCreateView(CreateView):
    model = Categoria
    fields = ['categoria']
    template_name = 'categoria_form.html'  
    success_url = reverse_lazy('productos:categoria-list')  
    def form_valid(self, form):
        # Modifica el dato antes de guardar
        form.instance.habilitado = 1  
        form.instance.es_producto = 1  
        return super().form_valid(form)
    
class CategoriaUpdateView(UpdateView):
    model = Categoria
    fields = ['categoria', 'habilitado']
    template_name = 'categoria_form.html'  
    success_url = reverse_lazy('productos:categoria-list')

def categoria_detail(request, pk):
    categoria = Categoria.objects.get(pk=pk)
    data={
        "id": categoria.id,
        'categoria': categoria.categoria,
        'habilitado': categoria.habilitado,
        'es_producto': categoria.es_producto,        
    }
    return JsonResponse(data)


class MedidaListView(ListView):
    model = Medida
    template_name = 'medida_list.html'
    context_object_name = 'medidas'

class MedidaCreateView(CreateView):
    model = Medida
    fields = ['medida']
    template_name = 'medida_form.html'  # Not used for modal, but required
    success_url = reverse_lazy('productos:medida-list')  # Change to your list view

    def form_valid(self, form):
        form.instance.es_producto=1
        return super().form_valid(form)

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.http import HttpResponse 
from django.contrib.auth.decorators import login_required   
# Create your views here.

class HomeView(TemplateView):
    template_name = 'home.html'

class VentaView(TemplateView):
    template_name = 'ventas.html'

@login_required
def bienvenida(request):
    if request.method == 'GET':
        return HttpResponse("Bienvenido a la página principal")
    elif request.method == 'PUT':
        return HttpResponse("Bienvenido a la página principal - POST")
    else:
        return HttpResponse("Método no permitido", status=405)


def contacto(request,correo):
    return HttpResponse("Se  enviará un correo a la dirección: "+correo)  

def about(request):
    return render(request, 'home.html')

apps/home/templates/ventas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Listado</h1>
    <a href="{% url 'home:homeapp' %}">Ventas</a>
</body>
</html>

apps/productos/templates/categoria_list.html
{% extends 'base.html' %}

{% block content %} 

        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="col-12 col-xl-12 mb-4 mb-xl-0 card-body">
                  <h4 class="card-title">Listado de categorías</h4>
                  <div class="row mb-3">
                    <div class="col-12 d-flex justify-content-end">
                      <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#crearCategoriaModal">
                        Crear Categoría
                      </button>
                    </div>
                  </div>
                  <div class="table-responsive">
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>
                            Categoría
                          </th>
                          <th>
                            Status
                          </th>
                          <th>
                            Acciones
                          </th>                          
                        </tr>
                      </thead>
                      <tbody>
                        {% for categoria in categorias %}
                        <tr>                          
                          <td>
                            {{ categoria.categoria }}
                          </td>
                          <td>                            
                            {% if categoria.habilitado %}
                              <i class="mdi mdi-check"></i>
                            {% else %}
                              <i class=" mdi mdi-close "></i> 
                            {% endif %}
                          </td>
                          <td>
                            <div class="template-demo">                              
                              <button type="button" class="btn btn-dark btn-icon-text btn-sm" data-toggle="modal" data-target="#crearCategoriaModal" data-url="{% url 'productos:categoria-detail' categoria.id %} ">
                                Editar                               
                              </button>
                              <button type="button" class="btn btn-danger btn-icon-text btn-sm">                                                                                   
                                Eliminar
                              </button>
                            </div>
                          </td>                          
                        </tr>  
                        {% endfor %}                      
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>         
            

            <!-- Modal -->
            <div class="modal fade" id="crearCategoriaModal" tabindex="-1" role="dialog" aria-labelledby="crearCategoriaLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <form method="post" action="{% url 'productos:categoria-create' %}">
                    {% csrf_token %}
                    <div class="modal-header">
                      <h5 class="modal-title" id="crearCategoriaLabel">Crear Categoría</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <div class="form-group">
                        <label for="categoria">Nombre de la categoría</label>
                        <input type="text" class="form-control" id="categoria" name="categoria" required>
                      </div>                      
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                      <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
{% endblock %}
    

apps/productos/templates/medida_list.html
{% extends 'base.html' %}

{% block content %}   


        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="col-12 col-xl-12 mb-4 mb-xl-0 card-body">
                  <h4 class="card-title">Listado de categorías</h4>
                  <div class="row mb-3">
                    <div class="col-12 d-flex justify-content-end">
                      <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#crearMedidaModal">
                        Crear Medida
                      </button>
                    </div>
                  </div>
                  <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>
                            Medida
                          </th>                          
                          <th>
                            Acciones
                          </th>                          
                        </tr>
                      </thead>
                      <tbody>
                        {% for medida in medidas %}
                        <tr>                          
                          <td>
                            {{ medida.medida }}
                          </td>                          
                          <td>
                            <div class="template-demo">                              
                              <button type="button" class="btn btn-dark btn-icon-text btn-sm">
                                Editar                               
                              </button>
                              <button type="button" class="btn btn-danger btn-icon-text btn-sm">                                                                                   
                                Eliminar
                              </button>
                           </div>
                          </td>                          
                        </tr>  
                        {% endfor %}                      
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>    
           

            <!-- Modal -->
            <div class="modal fade" id="crearMedidaModal" tabindex="-1" role="dialog" aria-labelledby="crearMedidaLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <form method="post" action="{% url 'productos:medida-create' %}">
                    {% csrf_token %}
                    <div class="modal-header">
                      <h5 class="modal-title" id="crearMedidaLabel">Crear Medida</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <div class="form-group">
                        <label for="categoria">Nombre de la medida</label>
                        <input type="text" class="form-control" id="medida" name="medida" required>
                      </div>                      
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                      <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
{% endblock %}
    